import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';

export default function SchemeDetails() {
  const { id } = useParams();
  const { language, t } = useLanguage();
  const [scheme, setScheme] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('overview');
  const [checkedDocs, setCheckedDocs] = useState([]);

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch(`${import.meta.env.VITE_API_URL || '/api'}/schemes/${id}?lang=${language}`);
        setScheme(await res.json());
      } catch (e) { console.error(e); }
      finally { setLoading(false); }
    })();
  }, [id, language]);

  const toggleDoc = (i) => {
    setCheckedDocs(prev => prev.includes(i) ? prev.filter(x => x !== i) : [...prev, i]);
  };

  const downloadChecklist = () => {
    if (!scheme) return;
    const lines = [
      `✅ ${scheme.name} — Application Checklist`,
      `${'─'.repeat(50)}`,
      `\n📋 Overview\n${scheme.description}`,
      `\n💰 Benefits\n${scheme.benefits}`,
      `\n📄 Required Documents`,
      ...scheme.documents.map((d, i) => `  ${checkedDocs.includes(i) ? '☑' : '☐'} ${d}`),
      `\n📝 How to Apply`,
      ...scheme.steps.map((s, i) => `  ${i + 1}. ${s}`),
      `\n🔗 Official Portal: ${scheme.officialLink}`,
      `\n─────────`,
      `Generated by GOV-AID | ${new Date().toLocaleDateString()}`
    ].join('\n');
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([lines], { type: 'text/plain' }));
    a.download = `${scheme.id}-checklist.txt`;
    a.click();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#FAFAF8] pt-[76px] flex items-center justify-center">
        <div className="text-center">
          <svg className="animate-spin w-8 h-8 text-[#FF9933] mx-auto mb-3" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
          </svg>
          <p className="text-sm text-gray-400">Loading scheme details...</p>
        </div>
      </div>
    );
  }

  if (!scheme) {
    return (
      <div className="min-h-screen bg-[#FAFAF8] pt-[76px] flex items-center justify-center">
        <div className="text-center">
          <span className="text-5xl block mb-3">😕</span>
          <h2 className="text-lg font-semibold text-gray-700 mb-2">Scheme not found</h2>
          <p className="text-sm text-gray-400 mb-4">The scheme you're looking for doesn't seem to exist.</p>
          <Link to="/eligibility" className="btn-secondary">{t('schemeBack')}</Link>
        </div>
      </div>
    );
  }

  const tabs = [
    { key: 'overview', label: t('schemeOverview'), emoji: '📋' },
    { key: 'eligibility', label: t('schemeEligibility'), emoji: '✅' },
    { key: 'documents', label: t('schemeDocuments'), emoji: '📄' },
    { key: 'steps', label: t('schemeSteps'), emoji: '📝' },
  ];

  return (
    <div className="min-h-screen bg-[#FAFAF8] pt-[76px]">
      {/* Header */}
      <div className="hero-gradient py-10 px-4">
        <div className="max-w-4xl mx-auto">
          <Link to="/eligibility"
            className="inline-flex items-center gap-1.5 text-sm text-blue-200/60 hover:text-white mb-4 transition-colors"
            id="back-to-results">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            {t('schemeBack')}
          </Link>
          <h1 className="text-xl md:text-2xl font-bold text-white mb-2">{scheme.name}</h1>
          <p className="text-sm text-blue-200/50">{scheme.ministry}</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 -mt-3">
        {/* Tabs */}
        <div className="card-warm p-1.5 flex gap-1 mb-5 overflow-x-auto" id="scheme-tabs">
          {tabs.map(tab => (
            <button key={tab.key} onClick={() => setActiveTab(tab.key)}
              className={`flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all ${
                activeTab === tab.key
                  ? 'bg-gradient-to-r from-orange-50 to-amber-50 text-[#FF9933] shadow-sm'
                  : 'text-gray-400 hover:text-gray-600 hover:bg-gray-50'
              }`}
              id={`tab-${tab.key}`}>
              <span className="text-base">{tab.emoji}</span>
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="card-warm p-7 animate-fade-in" id="scheme-content">
          {activeTab === 'overview' && (
            <div>
              <p className="text-sm text-gray-600 leading-relaxed mb-6">{scheme.description}</p>
              <div className="bg-orange-50 rounded-2xl p-5 border border-orange-100 mb-5">
                <h3 className="flex items-center gap-2 text-sm font-semibold text-[#E0820A] mb-2">
                  💰 {t('schemeBenefits')}
                </h3>
                <p className="text-sm text-gray-700 leading-relaxed">{scheme.benefits}</p>
              </div>
              <div className="flex flex-wrap gap-2">
                {scheme.tags.map(tag => (
                  <span key={tag} className="tag-pill">#{tag}</span>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'eligibility' && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { emoji: '🎂', label: 'Age Range', value: `${scheme.eligibility.minAge} – ${scheme.eligibility.maxAge} years` },
                { emoji: '👤', label: 'Gender', value: scheme.eligibility.gender.map(g => g.charAt(0).toUpperCase() + g.slice(1)).join(', ') },
                { emoji: '💵', label: 'Max Income', value: scheme.eligibility.maxIncome >= 9999999 ? 'No limit' : `₹${scheme.eligibility.maxIncome.toLocaleString()}/year` },
                { emoji: '📍', label: 'States', value: scheme.eligibility.states.includes('all') ? 'All States & UTs' : scheme.eligibility.states.join(', ') },
                { emoji: '🏷️', label: 'Categories', value: scheme.eligibility.categories.map(c => c.toUpperCase()).join(', ') },
                { emoji: '💼', label: 'Occupations', value: scheme.eligibility.occupations.includes('all') ? 'All occupations' : scheme.eligibility.occupations.map(o => o.charAt(0).toUpperCase() + o.slice(1)).join(', ') },
              ].map((item, i) => (
                <div key={i} className="bg-gray-50 rounded-xl p-4 border border-gray-100">
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className="text-lg">{item.emoji}</span>
                    <span className="text-xs text-gray-400 font-medium">{item.label}</span>
                  </div>
                  <p className="text-sm text-gray-700 font-medium pl-7">{item.value}</p>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'documents' && (
            <div>
              <p className="text-sm text-gray-400 mb-4">Check off documents as you gather them ✓</p>
              <div className="space-y-2.5">
                {scheme.documents.map((doc, i) => (
                  <button key={i} onClick={() => toggleDoc(i)}
                    className={`w-full flex items-center gap-3 rounded-xl p-3.5 text-left transition-all border ${
                      checkedDocs.includes(i)
                        ? 'bg-emerald-50 border-emerald-200'
                        : 'bg-gray-50 border-gray-100 hover:border-gray-200'
                    }`}>
                    <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center flex-shrink-0 transition-colors ${
                      checkedDocs.includes(i) ? 'bg-emerald-500 border-emerald-500' : 'border-gray-300'
                    }`}>
                      {checkedDocs.includes(i) && (
                        <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                      )}
                    </div>
                    <span className={`text-sm ${checkedDocs.includes(i) ? 'text-emerald-700 line-through' : 'text-gray-700'}`}>
                      {doc}
                    </span>
                  </button>
                ))}
              </div>
              {checkedDocs.length > 0 && (
                <p className="text-xs text-emerald-600 mt-3 font-medium">
                  ✓ {checkedDocs.length} of {scheme.documents.length} documents ready
                </p>
              )}
            </div>
          )}

          {activeTab === 'steps' && (
            <div className="space-y-0">
              {scheme.steps.map((step, i) => (
                <div key={i} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#FF9933] to-[#F08030] text-white flex items-center justify-center text-xs font-bold flex-shrink-0 shadow-sm">
                      {i + 1}
                    </div>
                    {i < scheme.steps.length - 1 && <div className="w-px flex-1 bg-orange-100 my-1.5"></div>}
                  </div>
                  <div className="pb-6 pt-1.5">
                    <p className="text-sm text-gray-700 leading-relaxed">{step}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-3 mt-5">
          <a href={scheme.officialLink} target="_blank" rel="noopener noreferrer"
            className="btn-primary flex-1 justify-center py-3.5" id="official-link">
            🌐 {t('schemeOfficialLink')}
          </a>
          <button onClick={downloadChecklist}
            className="btn-outline flex-1 justify-center py-3.5" id="download-checklist">
            📥 {t('schemeDownload')}
          </button>
        </div>
      </div>
    </div>
  );
}
